# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
# 
# If you want to be able to access a string config[:site_title], for example:
#   
# site_title:
#   name: Site Title
#   type: string
#   default: My Site
#   
# 'name' is the name that appears in the edit form
# 
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
# 
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
# 
# Some Examples:
#   
# site_title:
#   name: Site Title
#   default: My Site
#   type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#   
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password

# TODO: add to site settings form
email:
  name: Email for mailers
  default: 'noreply@example.com'
  type: email

site_title:
  name: Site title
  default: My Fitness Club
  type: string

day_start:
  name: Day Start
  default: 8
  type: integer

day_end:
  name: Day End
  default: 23
  type: integer

time_zone:
  name: Time Zone
  default: 'Hawaii'
  type: string

primary_color:
  name: Primary color
  default: '#2b7ac5'
  type: string

topbar_bg_color:
  name: Top bar background color
  default: '#333333'
  type: string

cancellation_deadline:
  name: Reservation cancellation deadline
  default: 12
  type: integer
